// Run actual Chrome UI interactions against a local preview; no model/device experiments.
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(path.join(process.cwd(),'browser-loader.cjs'));
const {chromium}=require('playwright');
const root=fileURLToPath(new URL('../',import.meta.url));
const base=process.env.ATLAS_PREVIEW_URL||'http://127.0.0.1:8766/';
const chrome=process.env.ATLAS_CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const output=path.join(root,'research/deepseek/validation');await fs.mkdir(output,{recursive:true});
const family=JSON.parse(await fs.readFile(path.join(root,'data/families/deepseek/family.json'),'utf8'));
const catalog=JSON.parse(await fs.readFile(path.join(root,'data/catalog.json'),'utf8'));
const families=Object.fromEntries(await Promise.all(catalog.families.map(async f=>[f.id,JSON.parse(await fs.readFile(path.join(root,f.path),'utf8'))])));
const browser=await chromium.launch({executablePath:chrome,headless:true,args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(15000);
const errors=[],failedResponses=[],checks=[];
const record=(name,detail)=>{checks.push({name,detail});console.log('PASS '+name)};
const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400&&new URL(r.url()).origin===new URL(base).origin)failedResponses.push({url:r.url(),status:r.status()})})};watch(page);
const goto=async(route,p=page)=>{
 await p.goto(base+route,{waitUntil:'networkidle'});
 if(route.startsWith('#/family/')){
  const parts=route.slice(2).split('/'),f=families[parts[1]],m=parts[2]==='model'?f.models.find(m=>m.id===parts[3]):null;
  await p.waitForFunction(({name,model})=>document.title.includes('· '+name+' ·')&&(!model||document.querySelector('#content h1')?.textContent===model),{name:f.name,model:m?.name});
 if(parts[2]==='compute')await p.locator(`#compute-atlas[data-model="${parts[3]}"]`).waitFor();
 if(['cost','contracts','parallel','mechanisms'].includes(parts[2]))await p.locator(`#analysis-atlas[data-page="${parts[2]}"]`).waitFor();
 if(parts[2]==='mechanisms'&&parts[3])await p.locator(`#analysis-atlas[data-mechanism="${parts[3]}"]`).waitFor();
 }
 if(route==='#/compare')await p.locator('.cross-comparison').waitFor();
 assert.equal(await p.locator('.error').count(),0);await p.locator('main h1').first().waitFor();
};
const includes=async(locator,text)=>assert.ok((await locator.innerText()).includes(text),text);
const structureReady=async(p=page)=>{await p.locator('#structure-inspector h3').waitFor();await p.waitForFunction(()=>document.querySelector('#structure-canvas')?.dataset.rendered==='true')};
const noOverflow=async(p=page)=>{const v=await p.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth}));assert.ok(v.body<=v.viewport+1,JSON.stringify(v));return v};
const loadImages=async(selector,p=page)=>{for(const img of await p.locator(selector).all()){await img.scrollIntoViewIfNeeded();await img.evaluate(el=>el.decode())}};
try{
 await goto('#/');assert.equal(await page.locator('.family-card').count(),4);await includes(page.locator('#content'),'DeepSeek');record('home and DeepSeek entry','4 research entries');
 await page.locator('.family-card[href="#/family/deepseek"]').click();await page.locator('.family-label').waitFor();assert.equal(await page.locator('.stat b').first().innerText(),String(family.models.length));record('family overview',`${family.models.length} representative checkpoints`);
 await goto('#/family/deepseek/models');assert.equal(await page.locator('.model-card').count(),family.models.length);await page.locator('#search').fill('Distill');assert.equal(await page.locator('.model-card').count(),6);await page.locator('#search').fill('__no_matching_model__');assert.equal(await page.locator('.model-card').count(),0);await includes(page.locator('.empty'),'没有符合');await page.locator('#reset').click();assert.equal(await page.locator('.model-card').count(),family.models.length);
 for(const id of ['v3','v3.2','v4-flash','r1-distill-qwen-1.5b'])await page.locator(`input[data-compare="${id}"]`).check();await page.locator('#compare-bar a').click();await page.locator('#comparison table').waitFor();assert.equal(await page.locator('#comparison thead th').count(),5);await includes(page.locator('#comparison'),'1,777,088,000');await includes(page.locator('#comparison'),'671,877,944,064');await includes(page.locator('#comparison'),'未核验 / 未披露');await noOverflow();record('search, empty result, reset and comparison','6 Distills; V3/DSA/V4/GQA parameters and unknown storage remain distinct');

 await goto('#/family/deepseek/model/v3');await structureReady();assert.equal(await page.locator('#structure-node option').count(),61);await includes(page.locator('#content'),'163 个分片');await includes(page.locator('#content'),'91,991');await page.locator('#structure-node').selectOption('decoder-4');await page.locator('[data-module="routed"]').click();await includes(page.locator('#structure-matrices'),'256');await includes(page.locator('#structure-matrices'),'F8_E4M3');await includes(page.locator('#structure-matrices'),'weight_scale_inv');await page.locator('#structure-fallback-link').click();await page.locator('[data-node="decoder-61"]').click();await includes(page.locator('#structure-inspector h3'),'61');await page.locator('#structure-group').selectOption('other');await page.locator('#structure-node').selectOption('mtp-1');await includes(page.locator('#structure-inspector'),'SharedHead.norm');await includes(page.locator('#structure-inspector'),'上游训练');record('V3 storage, layer navigation and separate MTP','61 main layers; actual FP8/scales; shared alias uncertainty visible');
 await goto('#/family/deepseek/model/v3.2');await structureReady();await page.locator('#structure-node').selectOption('decoder-4');await page.locator('[data-module="indexer"]').click();await includes(page.locator('.cache-note'),'top-k=2048');assert.ok((await page.locator('#structure-inspector a').last().getAttribute('href')).includes('/implementation/dsa/v3.2'));await page.locator('#structure-inspector a').last().click();await page.locator('.research-card').waitFor();await includes(page.locator('.research-card'),'DSA');record('DSA module to implementation','indexer cache and current-model topic jump');
 await goto('#/family/deepseek/model/v4-flash');await structureReady();assert.equal(await page.locator('#structure-node option').count(),43);await page.locator('#structure-node').selectOption('decoder-2');await page.locator('#structure-enter').click();await page.waitForFunction(()=>document.querySelector('#structure-labels')?.innerText.includes('mHC'));const label=page.locator('.scene-label').filter({hasText:'mHC'}).first();const box=await label.boundingBox();assert.ok(box);await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await includes(page.locator('#structure-matrices'),'hc_attn_fn');await includes(page.locator('#structure-matrices'),'24 × '+4*family.models.find(m=>m.id==='v4-flash').facts.hidden.value);assert.ok((await page.locator('#structure-inspector a').last().getAttribute('href')).includes('/implementation/mhc/v4-flash'));
 const draws=+(await page.locator('#structure-canvas').getAttribute('data-draw-count'));await page.locator('#structure-canvas').focus();await page.keyboard.press('ArrowRight');await page.locator('#structure-zoom-in').click();await page.waitForFunction(before=>+document.querySelector('#structure-canvas').dataset.drawCount>before,draws);await page.locator('#structure').screenshot({path:path.join(output,'v4-structure.png')});record('V4 3D canvas picking and mHC matrices','43 main layers; four streams; real canvas click, rotate and zoom');
 await goto('#/family/deepseek/model/r1-distill-qwen-1.5b');await structureReady();await page.locator('[data-module="ffn"]').click();assert.ok((await page.locator('#structure-inspector a').last().getAttribute('href')).includes('/implementation/ffn/'));assert.equal(await page.locator('[data-module="routed"]').count(),0);await includes(page.locator('.cache-note'),'KV cache');record('Distill GQA/Dense topic routing','no MoE module; FFN link and GQA cache');

 await goto('#/family/deepseek/compute/v3/mtp-1');await page.locator('#compute-results .compute-step').first().waitFor();await includes(page.locator('#compute-results'),'model.layers.61');assert.ok(!(await page.locator('#compute-results').innerText()).includes('model.layers.-1'));await page.locator('#compute-phase').selectOption('decode');await includes(page.locator('#compute-results'),'decode');await page.locator('#compute-search').fill('__no_matching_step__');await includes(page.locator('#compute-results .empty'),'没有匹配');await page.locator('#compute-search').fill('');record('V3 compute MTP source index and phase/search','source layer 61; empty filter works');
 await goto('#/family/deepseek/compute/v3.2/decoder-4');await page.locator('#compute-phase').selectOption('decode');const paths=await page.locator('#compute-path option').evaluateAll(es=>es.map(e=>e.value));const absorbed=paths.find(v=>v==='dsa-decode');assert.ok(absorbed);await page.locator('#compute-path').selectOption(absorbed);await page.locator('#compute-backend').selectOption('ascend');assert.ok(await page.locator('#compute-results .compute-step').count()>0);assert.equal(await page.locator('#compute-results .api-card h3').first().innerText(),'Ascend NPU');await noOverflow();record('compute phase, implementation-path and backend filters',absorbed);
 await goto('#/family/deepseek/compute/v4-flash/mtp-1');await page.locator('#compute-search').fill('h_proj');await includes(page.locator('#compute-results'),'mtp.0.h_proj.weight');await includes(page.locator('#compute-model-info'),'未读取权重值');record('V4 MTP namespace and storage boundary','mtp.0 is distinct from main layer indices');

 await goto('#/family/deepseek/model/v4-flash-dspark');await structureReady();await includes(page.locator('#content'),'本版文件头已核对');assert.ok(!(await page.locator('#content').innerText()).includes('实际存储未审计'));await page.locator('#structure-group').selectOption('other');assert.equal(await page.locator('#structure-node option[value^="dspark-"]').count(),3);assert.deepEqual(await page.locator('#structure-node option[value^="dspark-"]').evaluateAll(es=>es.map(e=>e.textContent.split(' · ')[0])),['DSpark 1','DSpark 2','DSpark 3']);await page.locator('#structure-node').selectOption('dspark-3');await includes(page.locator('#structure-inspector h3'),'DSpark 3');await page.locator('[data-module="dspark-heads"]').click();await includes(page.locator('#structure-matrices'),'markov_head.markov_w1.weight');await includes(page.locator('#structure-matrices'),'confidence_head.proj.weight');assert.ok((await page.locator('#structure-inspector a').last().getAttribute('href')).includes('/implementation/dspark/'));await page.locator('#structure').screenshot({path:path.join(output,'dspark-structure.png')});await goto('#/family/deepseek/compute/v4-flash-dspark/dspark-3');await page.locator('#compute-search').fill('Markov');await includes(page.locator('#compute-results'),'confidence');await goto('#/family/deepseek/technology/speculation');await includes(page.locator('#content'),'num_nextn_predict_layers=1');await includes(page.locator('#content'),'Markov');record('DSpark stages, matrix/head and protocol paths','3 actual stages; Markov/confidence; config/block/service count distinctions');
 await goto('#/family/deepseek/implementation');assert.equal(await page.locator('.research-card').count(),11);await goto('#/family/deepseek/implementation/all/r1-distill-qwen-7b');assert.equal(await page.locator('.research-card').count(),4);assert.ok(!(await page.locator('.research-card').allInnerTexts()).some(t=>t.startsWith('MoE')));await goto('#/family/deepseek/hardware');assert.equal(await page.locator('.hardware-table tbody tr').count(),2);await includes(page.locator('#content'),'CANN');await goto('#/family/deepseek/ascend');assert.equal(await page.locator('.research-card').count(),7);await includes(page.locator('#content'),'不纳入本次验收');assert.ok(!(await page.locator('#content').innerText()).includes('用户暂缓'));assert.equal(family.acceptanceScope.deviceExperimentsRequired,false);record('implementation, platform conditions and optional future research','11 topics; 2 conditional platforms; 7 optional candidates excluded from acceptance');
 await goto('#/family/deepseek/implementation/cann/v4-flash-dspark');await includes(page.locator('#content'),'9.2.0-beta.2');await includes(page.locator('#content'),'30');await goto('#/family/deepseek/technology/cann');await includes(page.locator('#content'),'aclnnFusedInferAttentionScoreV4/V5');await includes(page.locator('#content'),'libopapi');assert.ok(await page.locator('.article a[href*="/blob/"]').count()>50);await page.screenshot({path:path.join(output,'cann-sources.png')});record('CANN fixed source/package and API version distinction','30 families; SDK availability separate from installed operator libraries; source/ABI/runtime distinct');
await goto('#/family/deepseek/report/all');assert.equal(await page.locator('.article h2').count(),11);assert.equal(await page.locator('.article img').count(),4);await includes(page.locator('.article'),'本轮实际 header 为 I64');await includes(page.locator('.article'),'设备实验不作为未完成项或验收前置条件');await includes(page.locator('.article'),'静态成本、算子契约与系统分析');await loadImages('.article img');await goto('#/family/deepseek/gallery');assert.equal(await page.locator('.gallery figure').count(),4);await loadImages('.gallery img');record('full report and figure gallery','11 chapters; 4 loaded SVG diagrams');

 await goto('#/family/deepseek/sources');assert.equal(await page.locator('.download').count(),family.downloads.length);await page.locator('#download-search').fill('xlsx');assert.equal(await page.locator('.download').count(),2);await page.locator('#download-search').fill('模型与算子.xlsx');assert.equal(await page.locator('.download').count(),1);const [download]=await Promise.all([page.waitForEvent('download'),page.locator('.download a[download]').click()]);assert.equal(download.suggestedFilename(),'DeepSeek-模型与算子.xlsx');await page.locator('#download-search').fill('');
 for(const entry of family.downloads){const response=await context.request.get(new URL(entry.path,base).href);assert.equal(response.status(),200,entry.path);const raw=await response.body();assert.equal(raw.length,entry.bytes,entry.path);assert.equal(createHash('sha256').update(raw).digest('hex'),entry.sha256,entry.path)}record('all attachments over HTTP and actual XLSX download',`${family.downloads.length} HTTP 200 responses, sizes and SHA-256 match`);
 await goto('document.html?file='+encodeURIComponent('assets/deepseek/DeepSeek-研究报告.md'));await page.locator('#document h1').waitFor();assert.equal(await page.locator('#collection').innerText(),'DeepSeek 来源与下载');assert.equal(await page.locator('#document img').count(),4);await loadImages('#document img');record('Markdown online reader','4 relative images resolved; correct family return link');

 const scenarioDownload=async(button)=>{const [file]=await Promise.all([page.waitForEvent('download'),page.locator(button).click()]);return JSON.parse(await fs.readFile(await file.path(),'utf8'))};
 await goto('#/family/deepseek/cost/v3');assert.equal(await page.locator('#cost-model option').count(),21);const baseCost=(await scenarioDownload('#cost-export')).result;await page.locator('#cost-batch').fill('2');const doubleCost=(await scenarioDownload('#cost-export')).result;assert.equal(doubleCost.contractionFlops,2*baseCost.contractionFlops);assert.equal(doubleCost.sequenceCacheBytes,2*baseCost.sequenceCacheBytes);await page.locator('#cost-path').selectOption('expanded');const expandedCost=(await scenarioDownload('#cost-export')).result;assert.ok(expandedCost.mainKvBytes>doubleCost.mainKvBytes);await page.locator('#cost-batch').fill('0');assert.equal(await page.locator('#cost-export').isDisabled(),true);await includes(page.locator('#cost-result'),'batch');await page.locator('#cost-batch').fill('1');await page.locator('#cost-history').fill('');assert.equal(await page.locator('#cost-export').isDisabled(),true);await page.locator('#cost-history').fill('0');await page.locator('#cost-phase').selectOption('verify');assert.equal(await page.locator('#cost-logits').inputValue(),'all');const verifyCost=(await scenarioDownload('#cost-export')).result;assert.equal(verifyCost.input.query,5);assert.equal(verifyCost.measuredThroughput,null);await page.locator('#cost-layer').selectOption('decoder-61');const layerCost=(await scenarioDownload('#cost-export')).result;assert.equal(layerCost.rows.reduce((n,r)=>n+r.layers,0),1);assert.equal(layerCost.headFlops,0);await page.screenshot({path:path.join(output,'static-cost.png')});record('static cost inputs, precision/path and current JSON export','batch scaling; latent/expanded caches; invalid input; target verify and one-layer scope');
 await page.locator('#cost-phase').selectOption('prefill');await page.locator('#cost-layer').selectOption('all');for(const model of family.models){await page.locator('#cost-model').selectOption(model.id);assert.equal(await page.locator('#cost-result .analysis-error').count(),0);assert.ok(!(await page.locator('#cost-result').innerText()).includes('NaN'))}record('cost calculator for all 21 checkpoints','every main model produces finite static results');

 await goto('#/family/deepseek/contracts');assert.equal(await page.locator('#contract-operator option').count(),30);await page.locator('#contract-gamma').fill('64');await page.locator('#contract-check-result [data-status="contradiction"]').waitFor();await page.locator('#contract-gamma').fill('128');await page.locator('#contract-check-result [data-status="incomplete_static_check"]').waitFor();await includes(page.locator('#contract-check-result'),'其他条件');await page.locator('#contract-operator').selectOption('swiglu');await page.locator('#contract-x').fill('2,127');await page.locator('#contract-check-result [data-status="contradiction"]').waitFor();await page.locator('#contract-x').fill('2,128');await page.locator('#contract-dim').fill('2');await page.locator('#contract-check-result [data-status="contradiction"]').waitFor();await page.locator('#contract-dim').fill('-1');await page.locator('#contract-layout').selectOption('NZ');await page.locator('#contract-check-result [data-status="contradiction"]').waitFor();await page.locator('#contract-layout').selectOption('ND');await page.locator('#contract-x').fill('invalid');await includes(page.locator('#contract-check-result'),'格式错误');await page.locator('#contract-x').fill('2,128');await page.locator('#contract-operator').selectOption('grouped-matmul');await page.locator('#contract-document').selectOption('aclnnGroupedMatmulV4');await page.locator('#contract-search').fill('__no_contract__');await includes(page.locator('#contract-results .empty'),'没有匹配');await page.locator('#contract-search').fill('');await includes(page.locator('#contract-check-result'),'尚未编码');await page.screenshot({path:path.join(output,'cann-contracts.png')});record('CANN contract filters, necessary predicates and unknown boundaries','30 families; RMSNorm/SwiGLU contradictions; invalid shapes; API V4 subset; no false runtime pass');
 for(const op of await page.locator('#contract-operator option').evaluateAll(es=>es.map(e=>e.value))){await page.locator('#contract-operator').selectOption(op);assert.ok(await page.locator('#contract-results tbody tr').count()>0)}record('all 30 CANN contract families load','document tables or explicitly limited API forwarding evidence');

 await goto('#/family/deepseek/parallel');const parallelBase=(await scenarioDownload('#parallel-export')).result;assert.equal(parallelBase.ep,8);assert.equal(await page.locator('.rank-grid>div').count(),8);await page.locator('#parallel-tp').fill('3');assert.equal(await page.locator('#parallel-export').isDisabled(),true);await includes(page.locator('#parallel-result'),'整除');await page.locator('#parallel-tp').fill('2');await page.locator('#parallel-remote').selectOption('0');const localOnly=(await scenarioDownload('#parallel-export')).result;assert.equal(localOnly.moeSendBytes,0);await page.locator('#parallel-tp').fill('1');const singleTP=(await scenarioDownload('#parallel-export')).result;assert.equal(singleTP.tpRingSendBytes,0);assert.equal(singleTP.measuredCommunicationTime,null);await includes(page.locator('#analysis-atlas'),'MRv1');await includes(page.locator('#analysis-atlas'),'MRv2');await page.screenshot({path:path.join(output,'parallel-analysis.png')});record('parallel capacity, route assumptions, collectives and P/D','TP/DP/EP groups; invalid equal split; local-only routes; TP=1 ring; current assumptions export');

 await goto('#/compare');assert.equal(await page.locator('#cross-models input').count(),42);assert.equal(await page.locator('#cross-result thead th').count(),4);await page.locator('.comparison-cache summary').last().click();await includes(page.locator('#cross-result'),'Cache 表示与范围');await includes(page.locator('#cross-result'),'压缩');await page.locator('.cross-comparison details').first().locator('summary').click();await page.locator('#cross-family').selectOption('kimi');await page.locator('input[data-cross="kimi:k1"]').check();await includes(page.locator('#cross-result'),'未核对 / 未收录');assert.equal(await page.locator('#cross-result thead th').count(),5);await page.locator('#cross-search').fill('__no_cross_model__');await includes(page.locator('#cross-models .empty'),'没有匹配');await page.locator('#cross-reset').click();assert.equal(await page.locator('#cross-result thead th').count(),4);await page.locator('#cross-family').selectOption('deepseek');await page.locator('input[data-cross="deepseek:v3"]').check();await page.locator('input[data-cross="deepseek:v3.2"]').check();await page.locator('input[data-cross="deepseek:r1"]').check();await page.locator('input[data-cross="deepseek:r1-zero"]').click();assert.equal(await page.locator('input[data-cross="deepseek:r1-zero"]').isChecked(),false);await includes(page.locator('#cross-result'),'最多比较 6');await page.locator('#cross-reset').click();await page.screenshot({path:path.join(output,'cross-family.png')});record('cross-family selection, source depth and unknown facts','42 entries; DeepSeek/Kimi/GLM defaults; historical nulls; filters, reset and six-model limit');

 for(const kind of ['mla','dsa','compression','mhc','dspark']){await goto('#/family/deepseek/mechanisms/'+kind);assert.equal(await page.locator('[data-demo-step]').count(),5);for(let step=0;step<5;step++){assert.equal(await page.locator('.demo-stage').getAttribute('data-step'),String(step));assert.ok(!(await page.locator('#demo-result').innerText()).includes('NaN'));if(step<4)await page.locator('#demo-next').click()}await page.locator('#demo-prev').click();assert.equal(await page.locator('.demo-stage').getAttribute('data-step'),'3');await page.locator('#demo-reset').click();assert.equal(await page.locator('.demo-stage').getAttribute('data-step'),'0');await page.locator('[data-demo-step="4"]').click();if(kind==='mla'){await page.locator('#demo-rank').fill('');await includes(page.locator('#demo-result'),'允许范围');await page.locator('#demo-rank').fill('4');await includes(page.locator('#demo-result'),'两条输出')}if(kind==='compression'){await page.locator('#demo-tokens').fill('3');await includes(page.locator('#demo-result'),'未满块状态')}if(kind==='dspark'){await page.locator('#demo-threshold').fill('0.95');await includes(page.locator('#demo-result'),'提交 token 序列')}await page.screenshot({path:path.join(output,'mechanism-'+kind+'.png')})}record('five mechanisms, all steps, controls and restart','MLA/DSA/compression/mHC/DSpark; 25 stages; teaching boundaries and fixed references');

 for(const model of family.models){await goto('#/family/deepseek/model/'+model.id);await structureReady();assert.equal(await page.locator('#structure-node option').count(),model.facts.layers.value);await noOverflow()}record('all 21 model detail pages','all structure maps load and desktop widths fit');
 await goto('#/family/kimi/model/k3');await structureReady();assert.equal(await page.locator('#structure-node option').count(),93);await page.locator('#structure-node').selectOption('decoder-93');await includes(page.locator('#structure-inspector h3'),'MLA');await goto('#/family/kimi/compute/k3');await page.locator('#compute-results .compute-step').first().waitFor();assert.equal(await page.locator('#compute-phase').count(),0);await goto('#/family/glm/models');assert.ok(await page.locator('.model-card').count()>0);await page.locator('.model-card h3 a').first().click();await page.locator('main h1').waitFor();assert.equal(await page.locator('.error').count(),0);await goto('reports/openbmb/');await includes(page.locator('main'),'OpenBMB');record('existing family and organization regression','Kimi 93 layers and compute; GLM detail; OpenBMB report');

 await page.setViewportSize({width:390,height:844});const mobile=[];
 for(const route of ['models','compare','model/v4-flash','model/v4-flash-dspark','compute/v3.2/decoder-4','compute/v4-flash-dspark/dspark-3','technology/speculation','implementation/cann/v4-flash-dspark','implementation','hardware','ascend','report/all','gallery','sources','cost','contracts','parallel','mechanisms/mla','mechanisms/dsa','mechanisms/compression','mechanisms/mhc','mechanisms/dspark']){await goto('#/family/deepseek/'+route);if(route.startsWith('model/'))await structureReady();mobile.push({route,...await noOverflow()})}await goto('#/compare');mobile.push({route:'global cross-family comparison',...await noOverflow()});await goto('#/family/deepseek/model/v4-flash');await structureReady();await page.locator('#structure-enter').click();await page.locator('#structure').screenshot({path:path.join(output,'mobile-structure.png')});record('390px mobile layout',mobile);
 const figurePage=await context.newPage();await figurePage.setViewportSize({width:1600,height:900});
 try{for(const fig of family.figures){await figurePage.setContent(`<html><head><link rel="icon" href="data:,"></head><body style="margin:0"><img src="${new URL(fig.path,base).href}" style="display:block;width:1600px"></body></html>`);await loadImages('img',figurePage);await figurePage.locator('img').screenshot({path:path.join(output,path.basename(fig.path,'.svg')+'.png')})}}finally{await figurePage.close()}

 const fallbackBrowser=await chromium.launch({executablePath:chrome,headless:true,args:['--disable-webgl','--disable-webgl2']});
 try{const fallback=await fallbackBrowser.newPage({viewport:{width:390,height:844}});watch(fallback);await goto('#/family/deepseek/model/v4-flash',fallback);await fallback.locator('#structure-inspector h3').waitFor();assert.equal(await fallback.locator('#structure-canvas').isVisible(),false);assert.equal(await fallback.locator('#structure-table').getAttribute('open'),'');await fallback.locator('[data-node="decoder-43"]').click();await includes(fallback.locator('#structure-inspector h3'),'43');await fallback.locator('[data-module="routed"]').click();await includes(fallback.locator('#structure-matrices'),'256');await noOverflow(fallback);record('WebGL disabled: 2D fallback and matrix navigation','native browser flags; same layer/module data')}finally{await fallbackBrowser.close()}
 assert.deepEqual(errors,[]);assert.deepEqual(failedResponses,[]);record('console and network errors','none across tested pages');
 const result={status:'passed',date:'2026-10-02',browser:'Google Chrome via Playwright; WebGL UI',checks,consoleErrors:errors,failedResponses,screenshots:['cann-sources.png','v4-structure.png','dspark-structure.png','mobile-structure.png','lineage.png','v3-mla.png','v4-layers-mhc.png','dspark-protocol.png','static-cost.png','cann-contracts.png','parallel-analysis.png','cross-family.png','mechanism-mla.png','mechanism-dsa.png','mechanism-compression.png','mechanism-mhc.png','mechanism-dspark.png'],scope:'Static website UI and HTTP attachment checks; no model inference or Ascend experiments'};
 await fs.writeFile(path.join(output,'browser-validation.json'),JSON.stringify(result,null,2)+'\n');
 console.log('BROWSER VALIDATION PASSED: '+checks.length+' groups');
}catch(e){await fs.writeFile(path.join(output,'browser-failure.json'),JSON.stringify({url:page.url(),message:e.message,errors,failedResponses,checks},null,2));try{await page.screenshot({path:path.join(output,'failure.png'),fullPage:true,timeout:3000})}catch{}throw e}finally{await browser.close()}
